### ISSUE TITLE
Mix in files ?

### ISSUE THREAD

**Issue by constantinjoly** [Alicunde/HTML#3]
Hi, a lot of work here, thank you!

It seems that some files are the same in some differents components: 
index.html is the same in Grid, Input, Limit, Message and some others components. I did not visit all.
Is it wanted or an error?

Thank you again,

**Comment by salbatore** [comment]
Ups... Thank you so much for letting me know, I'm going to correct it right now. I think the components have been mixed.

Thank you very much!

**Comment by salbatore** [comment]
I just uploaded the changes, I'm creating a new version of the system, to review each component and follow a stricter style guide in the CSS. Certainly, there are quite a few components and sometimes it's hard to go through them all. Thank you very much for your help.
